"""Reconstruct CS_Credit_Approval_API workflow using the builder.

Validates the builder by producing JSON that matches the reference structure.
Extracts serviceAccount from the reference workflow for reuse.

Usage:
    python scripts/build_credit_approval.py
    python scripts/build_credit_approval.py --diff   # Show detailed differences
"""
import json
import sys
from pathlib import Path

# Ensure UTF-8 output on Windows
if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.workflow_builder import (
    WorkflowBuilder,
    WorkflowVariable,
    ViewParameter,
    WorkflowView,
    DistributionItem,
    ActionButton,
    TaskParameter,
    Assignment,
    DueDate,
    usertask,
    assignment,
    ionapi_flowpart,
    ifthenelse,
    subworkflow,
    build_condition,
    build_ido_load,
    build_ido_update,
)
from src.workflow_builder.ionapi import ApiOutput

# Paths
REFERENCE_PATH = Path(__file__).parent.parent / "reference" / "CS_Credit_Approval_API.json"
OUTPUT_DIR = Path(__file__).parent.parent / "output"
OUTPUT_PATH = OUTPUT_DIR / "CS_Credit_Approval_Clone.json"


def load_reference() -> dict:
    """Load the reference workflow JSON."""
    with open(REFERENCE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def extract_service_account(reference: dict) -> str:
    """Extract serviceAccount from the first ionapi flowpart in the reference."""
    for fp in reference["sequentialFlow"]["flowParts"]:
        if fp["_type"] == "ionapi":
            return fp["serviceAccount"]
        if fp["_type"] == "subworkflow":
            for sub_fp in fp["subFlow"]["flowParts"]:
                if sub_fp["_type"] == "ionapi":
                    return sub_fp["serviceAccount"]
    raise ValueError("No ionapi flowpart with serviceAccount found in reference")


def build_credit_approval(service_account: str) -> dict:
    """Build the CS_Credit_Approval_API workflow using the builder."""

    builder = WorkflowBuilder(
        name="CS_Credit_Approval_Clone",
        description="CSI Credit Approval (generated by WorkflowBuilder)",
    )

    # --- Variables (same order as reference) ---
    for var_def in [
        WorkflowVariable("ApproveReject"),
        WorkflowVariable("OldCreditLimit", workflow_input=True),
        WorkflowVariable("CustNum", workflow_input=True),
        WorkflowVariable("RowPointer", workflow_input=True),
        WorkflowVariable("Filter"),
        WorkflowVariable("CustName", workflow_input=True),
        WorkflowVariable("NewCreditLimit", workflow_input=True),
        WorkflowVariable("MGConfig", workflow_input=True),
        WorkflowVariable("UpdatePropertyValue"),
        WorkflowVariable("ItemID"),
    ]:
        builder.add_variable(var_def)

    # --- View ---
    builder.add_view(WorkflowView(
        name="CustomerDrillBack",
        view_set_name="infor.syteline (SyteLineViews)",
        view_name="CustomerView",
        parameters=[
            ViewParameter("AccountingEntity", value=""),
            ViewParameter("Location", value=""),
            ViewParameter("LogicalId", value=""),  # Auto-injected from tenant config
            ViewParameter("ID1", variable="CustNum"),
        ],
    ))

    # --- Notify usertask (seq 3) ---
    # NOTE: Replace placeholders with your actual user GUIDs and names
    notify_distribution = [
        DistributionItem("<USER_GUID_3>", description="<User 3>"),
        DistributionItem("<USER_GUID_1>", description="<User 1>"),
        DistributionItem("<USER_GUID_2>", description="<User 2>"),
    ]
    notify_params = [
        TaskParameter(label="Customer Drill Back", sequence_number=4, view="CustomerDrillBack"),
        TaskParameter(label="New Credit Limit", sequence_number=2, variable="NewCreditLimit"),
        TaskParameter(label="Status", sequence_number=3, variable="ApproveReject"),
        TaskParameter(label="ID", sequence_number=1, variable="CustNum"),
        TaskParameter(label="Name", sequence_number=0, variable="CustName"),
    ]
    notify_task = usertask(
        name="Notify",
        seq=3,
        task_type="NOTIFICATION",
        message=(
            "Customer -  [CustName] -  Newly requested Credit Limit "
            "of [NewCreditLimit] has been [ApproveReject]."
        ),
        distribution=notify_distribution,
        parameters=notify_params,
        propagate_notes=True,
    )

    # --- Update Record subworkflow (seq 2) ---

    # SetupFilter assignment (seq 1)
    setup_filter = assignment(
        name="SetupFilter",
        seq=1,
        assignments=[
            Assignment(
                variable_name="Filter",
                expression="\"RowPointer='\" & [RowPointer] & \"'\"",
                assignment_type="EXPRESSION_ASSIGNMENT",
            ),
        ],
    )

    # IfThenElse: IsApproved (seq 2)
    condition_xml = build_condition(
        name="IsApproved",
        variable="ApproveReject",
        operator="Equal",
        value="Approved",
    )

    set_limit_new = assignment(
        name="SetLimitNew",
        seq=1,
        assignments=[
            Assignment(
                variable_name="UpdatePropertyValue",
                expression="NewCreditLimit",
                assignment_type="VARIABLE_ASSIGNMENT",
            ),
        ],
    )

    set_limit_old = assignment(
        name="SetLimitOld",
        seq=1,
        assignments=[
            Assignment(
                variable_name="UpdatePropertyValue",
                expression="OldCreditLimit",
                assignment_type="VARIABLE_ASSIGNMENT",
            ),
        ],
    )

    if_approved = ifthenelse(
        seq=2,
        condition_xml=condition_xml,
        true_branch=[set_limit_new],
        false_branch=[set_limit_old],
    )

    # Get Record ionapi (seq 3)
    get_record_api = build_ido_load(
        ido_name="SLCustomers",
        properties="Name,CustNum,CreditLimit,CustSeq,RowPointer",
        filter_var="Filter",
        config_var="MGConfig",
        output_mappings=[
            ApiOutput(
                wf_variable_name="ItemID",
                path="$.Items[0]._ItemId",
            ),
        ],
        service_account=service_account,
    )
    get_record = ionapi_flowpart("Get Record", seq=3, ionapi_dict=get_record_api)

    # Update Record ionapi (seq 4)
    update_body = json.dumps({
        "IDOName": "SLCustomers",
        "RefreshAfterSave": True,
        "Changes": [
            {
                "Action": 2,
                "ItemId": "$value(ItemID)",
                "Properties": [
                    {
                        "IsNull": False,
                        "Modified": True,
                        "Name": "CreditLimit",
                        "Value": "$value(UpdatePropertyValue)",
                    },
                    {
                        "IsNull": False,
                        "Modified": True,
                        "Name": "InWorkflow",
                        "Value": "0",
                    },
                ],
            }
        ],
    }, indent=2)

    update_record_api = build_ido_update(
        ido_name="SLCustomers",
        changes_body=update_body,
        variable_names_from_body=["UpdatePropertyValue", "ItemID"],
        config_var="MGConfig",
        output_mappings=[
            ApiOutput(
                wf_variable_name="ItemID",
                path="$.RefreshItems[0].ItemId",
            ),
        ],
        service_account=service_account,
    )
    update_record = ionapi_flowpart("Update Record", seq=4, ionapi_dict=update_record_api)

    # Subworkflow containing the above
    update_subworkflow = subworkflow(
        name="Update Record",
        seq=2,
        flowparts=[get_record, setup_filter, update_record, if_approved],
    )

    # --- Review usertask (seq 1) ---
    # NOTE: Replace placeholders with your actual user GUIDs and names
    review_distribution = [
        DistributionItem("<USER_GUID_1>", description="<User 1>", send_email=True),
        DistributionItem("<USER_GUID_2>", description="<User 2>", send_email=True),
        DistributionItem("<USER_GUID_3>", description="<User 3>", send_email=True),
    ]
    review_params = [
        TaskParameter(label="New Limit", sequence_number=1, read_only=False, variable="NewCreditLimit"),
        TaskParameter(label="Customer Drill Back", sequence_number=4, view="CustomerDrillBack"),
        TaskParameter(label="Name", sequence_number=0, variable="CustName"),
        TaskParameter(label="Old Limit", sequence_number=3, variable="OldCreditLimit"),
        TaskParameter(label="ID", sequence_number=2, variable="CustNum"),
    ]
    review_task = usertask(
        name="Review",
        seq=1,
        task_type="USER_TASK",
        message="Customer -  [CustName] - Credit Limit has changed and is requesting approval",
        distribution=review_distribution,
        parameters=review_params,
        action_buttons=[
            ActionButton("Reject", "Rejected", sequence_number=1),
            ActionButton("Approve", "Approved", sequence_number=0),
        ],
        action_button_variable="ApproveReject",
        priority="High",
        due_date=DueDate(),
    )

    # --- Assemble flow (order in flowParts array matches reference) ---
    builder.add_flowpart(notify_task)
    builder.add_flowpart(update_subworkflow)
    builder.add_flowpart(review_task)

    return builder.build()


def deep_compare(ref: object, gen: object, path: str = "") -> list[str]:
    """Recursively compare two structures, returning list of differences.

    Skips metadata fields (lastUpdatedBy, lastUpdatedOn, tenant, etc.)
    and the 'method' field (compared separately since key order may differ).
    """
    skip_keys = {"lastUpdatedBy", "lastUpdatedOn", "tenant", "activationDate", "archived", "sendToDataLake"}
    diffs = []

    if isinstance(ref, dict) and isinstance(gen, dict):
        all_keys = set(ref.keys()) | set(gen.keys())
        for key in sorted(all_keys):
            if key in skip_keys:
                continue
            full_path = f"{path}.{key}" if path else key
            if key not in ref:
                diffs.append(f"EXTRA in generated: {full_path}")
            elif key not in gen:
                diffs.append(f"MISSING in generated: {full_path}")
            elif key == "method":
                # Compare method as parsed JSON (key order independent)
                try:
                    ref_method = json.loads(ref[key])
                    gen_method = json.loads(gen[key])
                    diffs.extend(deep_compare(ref_method, gen_method, f"{full_path}(parsed)"))
                except (json.JSONDecodeError, TypeError):
                    if ref[key] != gen[key]:
                        diffs.append(f"DIFF {full_path}: method strings differ")
            elif key == "serializedAssignments":
                # Compare as parsed JSON
                try:
                    ref_parsed = json.loads(ref[key])
                    gen_parsed = json.loads(gen[key])
                    diffs.extend(deep_compare(ref_parsed, gen_parsed, f"{full_path}(parsed)"))
                except (json.JSONDecodeError, TypeError):
                    if ref[key] != gen[key]:
                        diffs.append(f"DIFF {full_path}: serialized strings differ")
            elif key == "dueDateJson":
                # Compare as parsed JSON
                try:
                    ref_parsed = json.loads(ref[key])
                    gen_parsed = json.loads(gen[key])
                    diffs.extend(deep_compare(ref_parsed, gen_parsed, f"{full_path}(parsed)"))
                except (json.JSONDecodeError, TypeError):
                    if ref[key] != gen[key]:
                        diffs.append(f"DIFF {full_path}: dueDateJson strings differ")
            else:
                diffs.extend(deep_compare(ref[key], gen[key], full_path))
    elif isinstance(ref, list) and isinstance(gen, list):
        if len(ref) != len(gen):
            diffs.append(f"LENGTH {path}: ref={len(ref)} gen={len(gen)}")
        for i in range(min(len(ref), len(gen))):
            diffs.extend(deep_compare(ref[i], gen[i], f"{path}[{i}]"))
    else:
        if ref != gen:
            diffs.append(f"DIFF {path}: ref={ref!r} gen={gen!r}")

    return diffs


def main():
    show_diff = "--diff" in sys.argv

    print("=" * 60)
    print("CS_Credit_Approval_API Clone Builder")
    print("=" * 60)

    # Load reference
    print(f"\nLoading reference: {REFERENCE_PATH}")
    reference = load_reference()

    # Extract serviceAccount
    service_account = extract_service_account(reference)
    print(f"Extracted serviceAccount: {service_account[:40]}...")

    # Build clone
    print("\nBuilding workflow clone...")
    clone = build_credit_approval(service_account)

    # Write output
    OUTPUT_DIR.mkdir(exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(clone, f, indent=2, ensure_ascii=False)
    print(f"Written to: {OUTPUT_PATH}")

    # Compare
    print("\n--- Structural Comparison ---")
    diffs = deep_compare(reference, clone)

    if not diffs:
        print("[OK] Generated workflow matches reference structure exactly!")
    else:
        print(f"[!!] Found {len(diffs)} difference(s):")
        for d in diffs:
            print(f"  - {d}")

    if show_diff:
        print("\n--- Full JSON Diff ---")
        import difflib

        ref_lines = json.dumps(reference, indent=2, ensure_ascii=False).splitlines(keepends=True)
        gen_lines = json.dumps(clone, indent=2, ensure_ascii=False).splitlines(keepends=True)
        diff = difflib.unified_diff(ref_lines, gen_lines, fromfile="reference", tofile="generated")
        sys.stdout.writelines(diff)

    # Summary
    print(f"\nVariables: {len(clone['variables'])}")
    print(f"Views: {len(clone['views'])}")
    print(f"Trees: {len(clone['trees'])}")
    print(f"Top-level flowparts: {len(clone['sequentialFlow']['flowParts'])}")

    return 0 if not diffs else 1


if __name__ == "__main__":
    sys.exit(main())
