"""
Test script to send Pulse Alert, Notification, and Task via ION Process Application API.
Tests multiline messages, emojis, and type-specific properties.

Usage:
    python send_pulse_all_types.py

Prerequisites:
    - Generate token first: python -m shared.auth ION/scripts
"""
import sys
from pathlib import Path

# Add parent to path for shared module
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import requests
import json
from shared.auth import get_auth_headers
from shared.config import get_base_url
from shared.tenant import get_users

# Configuration
LOGICAL_ID = "lid://infor.rpa.claudecode"
USER_IDENTITY = get_users().get('user1', {}).get('guid', '<USER_GUID>')

# API endpoints
ION_PROCESS_URL = get_base_url('IONSERVICES/process/application')
ALERT_URL = f"{ION_PROCESS_URL}/v1/pulse/alert/create"
NOTIFICATION_URL = f"{ION_PROCESS_URL}/v1/pulse/notification/create"
TASK_URL = f"{ION_PROCESS_URL}/v1/pulse/task/create"


def get_distribution():
    """Return standard distribution list."""
    return [
        {
            "identifier": USER_IDENTITY,
            "type": "USER",
            "sendMail": False
        }
    ]


def send_request(url: str, payload: dict, item_type: str):
    """Send a Pulse request and handle response."""
    headers = get_auth_headers()
    params = {"logicalId": LOGICAL_ID}

    print(f"\n{'='*60}")
    print(f"Sending {item_type}")
    print(f"{'='*60}")
    print(f"URL: {url}")
    print(f"Payload:\n{json.dumps(payload, indent=2)}")

    response = requests.post(url, headers=headers, json=payload, params=params)

    print(f"\nStatus Code: {response.status_code}")
    print(f"Response: {response.text}")

    if response.status_code == 200:
        result = response.json()
        print(f"\n[SUCCESS] {item_type} created with ID: {result.get('id')}")
        return result
    else:
        print(f"\n[FAILED] {item_type} failed")
        return None


def send_alert():
    """
    Send an ALERT with:
    - Multiline message with emojis
    - details (TreeLevel structure - unique to alerts)
    - dueDate
    """
    message = """🚨 CRITICAL SYSTEM ALERT 🚨

Server: PROD-DB-PRIMARY
Status: DISK SPACE CRITICAL

⚠️ Database server is running low on disk space.
Immediate action required to prevent service disruption.

📊 Current Usage: 94.7%
📁 Available: 127 GB of 2 TB
⏰ Estimated Full: ~18 hours

Please investigate and take corrective action immediately.

--
Automated Alert from Infrastructure Monitoring
Generated by Claude Code Integration Test"""

    payload = {
        "message": message,
        "category": "Infrastructure",
        "dueDate": "2026-01-30T08:00:00Z",
        "distribution": get_distribution(),
        "details": {
            "name": "Server Metrics",
            "properties": [
                {"name": "Server Name", "value": "PROD-DB-PRIMARY", "dataType": "STRING"},
                {"name": "Environment", "value": "Production", "dataType": "STRING"},
                {"name": "Alert Level", "value": "CRITICAL", "dataType": "STRING"},
                {"name": "Disk Usage %", "value": "94.7", "dataType": "DECIMAL"},
                {"name": "Available GB", "value": "127", "dataType": "INTEGER"},
                {"name": "Total GB", "value": "2048", "dataType": "INTEGER"}
            ],
            "subLevels": [
                {
                    "name": "Disk Breakdown",
                    "properties": [
                        {"name": "Database Files", "value": "1456 GB", "dataType": "STRING"},
                        {"name": "Transaction Logs", "value": "312 GB", "dataType": "STRING"},
                        {"name": "Temp Files", "value": "89 GB", "dataType": "STRING"},
                        {"name": "Backups", "value": "64 GB", "dataType": "STRING"}
                    ]
                },
                {
                    "name": "Recommended Actions",
                    "properties": [
                        {"name": "Action 1", "value": "Archive old transaction logs", "dataType": "STRING"},
                        {"name": "Action 2", "value": "Clean temp files older than 7 days", "dataType": "STRING"},
                        {"name": "Action 3", "value": "Move backups to archive storage", "dataType": "STRING"},
                        {"name": "Priority", "value": "IMMEDIATE", "dataType": "STRING"}
                    ]
                }
            ]
        }
    }

    return send_request(ALERT_URL, payload, "ALERT")


def send_notification():
    """
    Send a NOTIFICATION with:
    - Multiline message with emojis
    - parameters (flat key-value list - unique structure vs Alert's tree)
    - retention (30/60/90 days - unique to notifications)
    - contextId/subContextId (workflow tracking)
    """
    message = """📦 Order Shipment Update 📦

Your order has been shipped and is on its way!

📋 Order Details:
   Order #: ORD-2026-789456
   Shipped: January 29, 2026

🚚 Shipping Information:
   Carrier: FedEx Express
   Tracking #: 7891234567890

📍 Destination:
   Acme Industries
   123 Manufacturing Way
   Detroit, MI 48201

📅 Estimated Delivery: February 1, 2026

Track your package at fedex.com or click the link below.

Thank you for your business! 🙏

--
Infor CloudSuite Shipping Notification
This is an automated test message from Claude Code"""

    payload = {
        "message": message,
        "category": "Shipping",
        "retention": 60,  # Keep for 60 days (unique to notifications)
        "contextId": 789456,  # Order ID as context
        "subContextId": 1,    # Shipment sequence
        "distribution": get_distribution(),
        "parameters": [
            {"name": "Order Number", "value": "ORD-2026-789456", "dataType": "STRING"},
            {"name": "Customer", "value": "Acme Industries", "dataType": "STRING"},
            {"name": "Ship Date", "value": "2026-01-29", "dataType": "DATE"},
            {"name": "Carrier", "value": "FedEx Express", "dataType": "STRING"},
            {"name": "Tracking Number", "value": "7891234567890", "dataType": "STRING"},
            {"name": "Estimated Delivery", "value": "2026-02-01", "dataType": "DATE"},
            {"name": "Package Weight", "value": "24.5", "dataType": "DECIMAL"},
            {"name": "Number of Packages", "value": "3", "dataType": "INTEGER"},
            {"name": "Ship To City", "value": "Detroit", "dataType": "STRING"},
            {"name": "Ship To State", "value": "MI", "dataType": "STRING"},
            {"name": "Insured Value", "value": "4500.00", "dataType": "DECIMAL"},
            {"name": "Signature Required", "value": "true", "dataType": "BOOLEAN"}
        ]
    }

    return send_request(NOTIFICATION_URL, payload, "NOTIFICATION")


def send_task():
    """
    Send a TASK with:
    - Multiline message with emojis
    - parameters (flat list)
    - priority (HIGH/MEDIUM/LOW - unique to tasks)
    - dueDate
    - customActions (action buttons! - unique to tasks)
    """
    message = """✅ ACTION REQUIRED: Expense Report Approval ✅

Employee: Sarah Johnson (EMP-10042)
Department: Engineering
Submitted: January 28, 2026

💰 Expense Summary:
   Total Amount: $2,847.50
   Number of Items: 7
   Trip Purpose: Customer Site Visit - Chicago

📝 Expense Breakdown:
   ✈️ Airfare (Round Trip)     $684.00
   🏨 Hotel (3 nights)         $897.00
   🚗 Rental Car               $245.50
   ⛽ Fuel                      $67.00
   🍽️ Meals                    $312.00
   🚕 Ground Transportation    $142.00
   📋 Conference Registration  $500.00

📎 Attachments: 12 receipts uploaded

⚡ This expense is within your approval limit ($5,000).

Please review and take action using the buttons below.

--
Expense Management System
Workflow Instance: WF-2026-00456"""

    payload = {
        "message": message,
        "category": "Expense Approval",
        "priority": "HIGH",  # Unique to tasks: HIGH, MEDIUM, LOW
        "dueDate": "2026-01-31T17:00:00Z",
        "contextId": 2026456,  # Workflow instance ID
        "subContextId": 3,     # Step in workflow
        "distribution": get_distribution(),
        "parameters": [
            # This parameter is REQUIRED - must match customActions.parameterName
            {"name": "approvalDecision", "value": "", "dataType": "STRING"},
            {"name": "Employee Name", "value": "Sarah Johnson", "dataType": "STRING"},
            {"name": "Employee ID", "value": "EMP-10042", "dataType": "STRING"},
            {"name": "Department", "value": "Engineering", "dataType": "STRING"},
            {"name": "Report ID", "value": "EXP-2026-789", "dataType": "STRING"},
            {"name": "Total Amount", "value": "2847.50", "dataType": "DECIMAL"},
            {"name": "Currency", "value": "USD", "dataType": "STRING"},
            {"name": "Submit Date", "value": "2026-01-28", "dataType": "DATE"},
            {"name": "Trip Purpose", "value": "Customer Site Visit - Chicago", "dataType": "STRING"},
            {"name": "Number of Items", "value": "7", "dataType": "INTEGER"},
            {"name": "Receipts Attached", "value": "12", "dataType": "INTEGER"},
            {"name": "Policy Compliant", "value": "true", "dataType": "BOOLEAN"},
            {"name": "Approval Limit", "value": "5000.00", "dataType": "DECIMAL"}
        ],
        "customActions": {
            "parameterName": "approvalDecision",
            "buttons": [
                {"label": "Approve", "value": "APPROVED"},
                {"label": "Reject", "value": "REJECTED"},
                {"label": "Request More Info", "value": "MORE_INFO"},
                {"label": "Delegate", "value": "DELEGATE"}
            ]
        }
    }

    return send_request(TASK_URL, payload, "TASK")


if __name__ == "__main__":
    print("\n" + "="*60)
    print("ION Pulse API Test - All Three Types")
    print("Testing: Multiline messages, emojis, type-specific features")
    print("="*60)

    results = {}

    # Send all three types
    results['alert'] = send_alert()
    results['notification'] = send_notification()
    results['task'] = send_task()

    # Summary
    print("\n" + "="*60)
    print("SUMMARY")
    print("="*60)
    for item_type, result in results.items():
        if result:
            print(f"  {item_type.upper()}: ID {result.get('id')}")
        else:
            print(f"  {item_type.upper()}: FAILED")
    print("="*60)
    print("\nCheck your Infor OS Pulse inbox for all three items!")
