"""AES Configuration Builder -- programmatically manage SyteLine event handlers."""

from .models import EventAction, EventHandler
from .builder import AESBuilder
from .spec_handler import build_handler_from_spec
from .expressions import (
    # Action type constants
    ACTION_FINISH,
    ACTION_NOTIFY,
    ACTION_SET_VALUES,
    ACTION_LOAD_COLLECTION,
    ACTION_INVOKE_METHOD,
    ACTION_SEND_BOD,
    ACTION_BRANCH,
    ACTION_PROMPT,
    ACTION_UPDATE_RECORD,
    ACTION_GENERATE_EVENT,
    ACTION_CALL_WORKFLOW,
    ACTION_WAIT,
    ACTION_SLEEP,
    # Base expression functions
    condition,
    not_condition,
    property_modified,
    prop,
    var,
    global_const,
    event_param,
    result_expr,
    return_var,
    substitute,
    voting_result,
    db_function,
    if_expr,
    round_expr,
    configname,
    username,
    curdatetime,
    originator,
    # Compound patterns
    finish_unless_modified,
    finish_with_result,
    fail_if_rejected,
    # Parameter line builders
    set_variable_params,
    setvarvalues_params,
    setpropvalues_params,
    load_collection_params,
    invoke_method_params,
    call_workflow_params,
    notify_params,
    build_ion_workflow_start_params,
)

__all__ = [
    # Models
    "EventAction",
    "EventHandler",
    "AESBuilder",
    "build_handler_from_spec",
    # Action type constants
    "ACTION_FINISH",
    "ACTION_NOTIFY",
    "ACTION_SET_VALUES",
    "ACTION_LOAD_COLLECTION",
    "ACTION_INVOKE_METHOD",
    "ACTION_SEND_BOD",
    "ACTION_BRANCH",
    "ACTION_PROMPT",
    "ACTION_UPDATE_RECORD",
    "ACTION_GENERATE_EVENT",
    "ACTION_CALL_WORKFLOW",
    "ACTION_WAIT",
    "ACTION_SLEEP",
    # Base expressions
    "condition",
    "not_condition",
    "property_modified",
    "prop",
    "var",
    "global_const",
    "event_param",
    "result_expr",
    "return_var",
    "substitute",
    "voting_result",
    "db_function",
    "if_expr",
    "round_expr",
    "configname",
    "username",
    "curdatetime",
    "originator",
    # Compound patterns
    "finish_unless_modified",
    "finish_with_result",
    "fail_if_rejected",
    # Parameter builders
    "set_variable_params",
    "setvarvalues_params",
    "setpropvalues_params",
    "load_collection_params",
    "invoke_method_params",
    "call_workflow_params",
    "notify_params",
    "build_ion_workflow_start_params",
]
